apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      volumes:
      - name: hostpath-volume
        hostPath:
          path: "/data/example"
      containers:
      - name: k8s-demo
        image: vogti/k8s-demo:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: hostpath-volume
          mountPath: "/usr/src/app/data"
        env:
        - name: PERSISTENCE_TYPE
          value: "memory"
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-demo-secrets
              key: APP_PASSWORD
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: k8s-demo-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-demo-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: k8s-demo-secrets
              key: DB_NAME